version: '3.8'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    volumes:
      - ./src:/app/src

  postgres:
    container_name: db-postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql.log
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

networks:
  default:
    driver: bridge

