export const INVALID_OLD_PASSWORD = 'Old password is wrong';
export const INVALID_PASSWORD = 'Invalid password';
export const USER_NOT_FOUND = 'User not found';
export const ALBUM_NOT_FOUND = 'Album not found';
export const ARTIST_NOT_FOUND = 'Artist not found';
export const TRACK_NOT_FOUND = 'Track not found';
export const ERR = 'Unprocessable entity';
export const BAD_REQUEST = 'Bad request';
export const ERR_TOKEN = 'Invalid token';
